version: "3"

services:
  lucee:
    image: lucee/lucee:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/var/www
    environment:
      LUCEE_ADMIN_PASSWORD: "hello"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234567"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "mypassword"
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
